name: Build and publish nginx-rkvst image
on:
  release:
    types: ['published']

jobs:
  build-and-publish-images:
    name: Build and publish nginx-rkvst image
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: checkout master
        uses: actions/checkout@v2
        with:
          path: master
      - name: Build and push nginx-rkvst
        uses: docker/build-push-action@v2
        with:
          context: master/mainline/alpine
          push: ${{ github.event_name != 'pull_request' }}
          tags: mwilder26/rkvst-sbom:latest

  generate-sbom:
    name: Generate SBOM
    needs: build-and-publish-images
    runs-on: ubuntu-latest
    steps:
      - uses: anchore/sbom-action@v0.3.0
        with:
          image: mwilder26/rkvst-sbom:latest
          format: cyclonedx

  publish-sbom:
    name: Publish SBOM to RKVST
    needs: generate-sbom
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2d
      - uses: leflambeur/rkvst-sbom@v0.0.5
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        with:
          command: release
          asset_id: assets/f98c67d6-2b96-46a5-bcfe-575a75f13d67
          attachments: '["yewnorosen-nginx-rkvst_latest.cyclonedx/yewnorosen-nginx-rkvst_latest.cyclonedx"]'

  generate-and-publish-vulnerability-report:
    name: Scan SBOM for known Vulnerabilities
    runs-on: ubuntu-latest
    needs: publish-sbom
    steps:
      - uses: actions/download-artifact@v2
      - name: Install Grype
        run: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
      - name: Run Grype
        run: grype mwilder26/rkvst-sbom:latest -o cyclonedx > nginx-rkvst_latest_vuln_report.cyclonedx
      - uses: leflambeur/rkvst-sbom@v0.0.5
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        with:
          command: vuln_report
          asset_id: assets/f98c67d6-2b96-46a5-bcfe-575a75f13d67
          attrs: '{"component": "${{ github.repository }}", "description": "${{ github.event.release.tag_name }} Vulnerability Report - ${{ github.repository }}", "target_version": "${{ github.event.release.tag_name }}", "author": "${{ github.actor }}"}'
          latest_sbom: '{}'
          attachments: '["nginx-rkvst_latest_vuln_report.cyclonedx"]'
