on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: ./.github/actions/hello_world
        with:
          monnom: 'LÃ©o'
    #   - run: echo random-number "$RANDOM_NUMBER"
    #     shell: bash
    #     env:
    #       RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
